"use client";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Check, Clock3, FileText, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AccessShell } from "@/app/components/access-request/AccessShell";
import { ProfileSelector } from "@/app/components/access-request/ProfileSelector";
import { ProfileType, profileCopy } from "@/app/components/access-request/types";
import { useState } from "react";
export default function RequestStartPage() { const [profile, setProfile] = useState<ProfileType>(); const router = useRouter(); return <AccessShell><section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="font-heading text-sm font-semibold uppercase tracking-[.16em] text-success">Acesso à plataforma</p><h1 className="mt-4 text-4xl sm:text-5xl">Solicite seu acesso ao Chuva &amp; Safra</h1><p className="mt-5 max-w-xl text-lg text-muted-foreground">Escolha como você atua no campo e envie suas informações para análise. O cadastro será liberado após a validação dos dados e documentos.</p><Link href="/acompanhar-solicitacao" className="mt-7 flex max-w-xl items-center gap-4 rounded-xl border-2 border-primary bg-secondary p-4 text-interactive shadow-sm transition-colors hover:bg-primary hover:text-primary-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground"><Search className="size-5" aria-hidden="true" /></span><span><strong className="block font-heading text-base">Já enviou sua solicitação?</strong><span className="mt-0.5 block text-sm">Clique aqui para acompanhar o status com seu protocolo.</span></span></Link><ul className="mt-8 space-y-4 text-sm text-muted-foreground">{[[Clock3,"O processo leva poucos minutos."],[ShieldCheck,"Documentos são avaliados por um administrador."],[FileText,"Acompanhe o andamento com seu protocolo."],[Check,"Os dados devem corresponder aos documentos enviados."]].map(([I,t])=>{const Icon=I as typeof Clock3;return <li key={String(t)} className="flex gap-3"><Icon className="mt-0.5 size-5 text-success" aria-hidden="true" />{t as string}</li>})}</ul></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-8"><p className="text-sm font-semibold text-interactive">1. Escolha seu perfil</p><h2 className="mt-2 text-2xl">Como você atua no campo?</h2><p className="mt-2 text-sm text-muted-foreground">Você poderá revisar esta escolha no formulário.</p><div className="mt-6"><ProfileSelector value={profile} onChange={setProfile} /></div>{profile && <p className="mt-5 rounded-lg bg-success-soft p-3 text-sm text-foreground"><strong>{profileCopy[profile].label}</strong> selecionado. Você poderá alterar depois.</p>}<Button disabled={!profile} className="mt-6 w-full" onClick={()=>router.push(`/solicitar-acesso/formulario?perfil=${profile}`)}>Continuar</Button></div></div></section></AccessShell> }
